// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkz6dh1a8xQJsd-1JNwRdI5-VD42Wmois',
    appId: '1:859967241146:web:56130f42f7f3ae81137b83',
    messagingSenderId: '859967241146',
    projectId: 'fasum-app-1d76a',
    authDomain: 'fasum-app-1d76a.firebaseapp.com',
    databaseURL: 'https://fasum-app-1d76a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-1d76a.appspot.com',
    measurementId: 'G-KBXB1MHTY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWfp6DXxggE_PEHd0RxpICHv50danyN-c',
    appId: '1:859967241146:android:d9ea5575a5025d6d137b83',
    messagingSenderId: '859967241146',
    projectId: 'fasum-app-1d76a',
    databaseURL: 'https://fasum-app-1d76a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-1d76a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgcd05qoSwbv3XNDZLMNCdRE78ODz1vqI',
    appId: '1:859967241146:ios:c3ebf01ae122d7b6137b83',
    messagingSenderId: '859967241146',
    projectId: 'fasum-app-1d76a',
    databaseURL: 'https://fasum-app-1d76a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-1d76a.appspot.com',
    androidClientId: '859967241146-q6b6fi1uqi48s240u60n8qn4ieif1qs6.apps.googleusercontent.com',
    iosClientId: '859967241146-78lamu98es8rf64kq0f8s8q3vkgq9meb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgcd05qoSwbv3XNDZLMNCdRE78ODz1vqI',
    appId: '1:859967241146:ios:c3ebf01ae122d7b6137b83',
    messagingSenderId: '859967241146',
    projectId: 'fasum-app-1d76a',
    databaseURL: 'https://fasum-app-1d76a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-1d76a.appspot.com',
    androidClientId: '859967241146-q6b6fi1uqi48s240u60n8qn4ieif1qs6.apps.googleusercontent.com',
    iosClientId: '859967241146-78lamu98es8rf64kq0f8s8q3vkgq9meb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkz6dh1a8xQJsd-1JNwRdI5-VD42Wmois',
    appId: '1:859967241146:web:7b2fb2fb6ab82b1a137b83',
    messagingSenderId: '859967241146',
    projectId: 'fasum-app-1d76a',
    authDomain: 'fasum-app-1d76a.firebaseapp.com',
    databaseURL: 'https://fasum-app-1d76a-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-1d76a.appspot.com',
    measurementId: 'G-BQ1KSRZN6Z',
  );

}